"""Write the hook's tables from the prepared reference: building footprints, upgrade ids."""

import json


def _write_table(output, command, reference, about, lines):
    header = [f"/* generated by `python -m tools.prepare {command}` from {reference.name}: {about} */", "#pragma once"]
    output.write_text("\n".join([*header, *lines, ""]), encoding="utf-8", newline="\n")


def _hex(raw):
    return f"0x{int.from_bytes(raw.encode(), 'big'):08x}u"


def prepare_footprints(output, reference):
    data = json.loads(reference.read_text(encoding="utf-8"))
    rows = sorted(
        (raw, *data["footprints"][raw])
        for raw, unit in data["units"].items()
        if unit["structure"] and any(data["footprints"].get(raw, [0, 0]))
    )
    lines = [
        "typedef struct { unsigned type; unsigned short w, h; } Footprint;",
        "static const Footprint FOOTPRINTS[] = {",
        *(f"    {{{_hex(raw)}, {w}, {h}}}, /* {raw} */" for raw, w, h in rows),
        "};",
    ]
    _write_table(output, "footprints", reference, "pathing-texture bounds", lines)
    print(f"Footprints: {output} ({len(rows)} structures)")


def prepare_upgrades(output, reference):
    """Every upgrade id: the binary observation reports the observer's level of each (GetPlayerTechCount)."""
    raws = sorted(json.loads(reference.read_text(encoding="utf-8"))["upgrades"])
    lines = ["static const unsigned UPGRADES[] = {", *(f"    {_hex(raw)}, /* {raw} */" for raw in raws), "};"]
    _write_table(output, "upgrades", reference, "every upgrade id", lines)
    print(f"Upgrades: {output} ({len(raws)} upgrades)")
