"""Write the hook's tables from the prepared reference: building footprints, upgrade ids."""

import json


def prepare_footprints(output, reference):
    data = json.loads(reference.read_text(encoding="utf-8"))
    rows = sorted(
        (raw, *data["footprints"][raw])
        for raw, unit in data["units"].items()
        if unit["structure"] and any(data["footprints"].get(raw, [0, 0]))
    )
    lines = [
        f"/* generated by `python -m tools.prepare footprints` from {reference.name}: pathing-texture bounds */",
        "#pragma once",
        "typedef struct { unsigned type; unsigned short w, h; } Footprint;",
        "static const Footprint FOOTPRINTS[] = {",
        *(f"    {{0x{int.from_bytes(raw.encode(), 'big'):08x}u, {w}, {h}}}, /* {raw} */" for raw, w, h in rows),
        "};",
        "",
    ]
    output.write_text("\n".join(lines), encoding="utf-8", newline="\n")
    print(f"Footprints: {output} ({len(rows)} structures)")


def prepare_upgrades(output, reference):
    """Every upgrade id: the binary observation reports the observer's level of each (GetPlayerTechCount)."""
    raws = sorted(json.loads(reference.read_text(encoding="utf-8"))["upgrades"])
    lines = [
        f"/* generated by `python -m tools.prepare upgrades` from {reference.name}: every upgrade id */",
        "#pragma once",
        "static const unsigned UPGRADES[] = {",
        *(f"    0x{int.from_bytes(raw.encode(), 'big'):08x}u, /* {raw} */" for raw in raws),
        "};",
        "",
    ]
    output.write_text("\n".join(lines), encoding="utf-8", newline="\n")
    print(f"Upgrades: {output} ({len(raws)} upgrades)")
